export const productList = [
    { name: "Vivo 23e", price: 23000, category: "electronics" },
    { name: "Samsung Galaxy S20", price: 80000, category: "electronics" },
    { name: "Apple MacBook Pro", price: 120000, category: "electronics" },
    { name: "Nike Air Max", price: 7000, category: "clothing" },
    { name: "Levi's Jeans", price: 4000, category: "clothing" },
    { name: "Adidas Tracksuit", price: 10000, category: "clothing" },
    { name: "KitchenAid Stand Mixer", price: 25000, category: "home" },
    { name: "Philips Air Fryer", price: 8000, category: "home" },
    { name: "Dyson Vacuum Cleaner", price: 35000, category: "home" },
    { name: "Wilson Tennis Racket", price: 5000, category: "sports" },
    { name: "Yonex Badminton Racquet", price: 3000, category: "sports" },
    { name: "Spalding Basketball", price: 2000, category: "sports" },
    { name: "The Great Gatsby", price: 500, category: "books" },
    { name: "To Kill a Mockingbird", price: 600, category: "books" },
    { name: "Harry Potter and the Sorcerer's Stone", price: 700, category: "books" },
    { name: "L'Oréal Paris Shampoo", price: 300, category: "beauty" },
    { name: "Nivea Men's Face Wash", price: 200, category: "beauty" },
    { name: "MAC Lipstick", price: 1000, category: "beauty" },
    { name: "LEGO Classic Bricks", price: 2000, category: "toys" },
    { name: "Barbie Dreamhouse", price: 5000, category: "toys" },
    { name: "Hot Wheels Track Set", price: 1500, category: "toys" },
];

